# https://docs.colyseus.io/cloud/continuous-deployment/#example-workflow

name: Deploy to Colyseus Cloud

# deploy only new changes in server files
on:
  push:
    branches:
      - main
    paths:
      - "server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      applicationId: ${{ secrets.APPLICATION_ID }}
      token: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Trigger deployment
        run: |
          cd server
          npm install -g @colyseus/cloud
          npx @colyseus/cloud deploy --applicationId $applicationId --token $token
